# -*- coding: utf-8 -*-
"""Основной код бота (Webhook)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RqXZUwsQb1xq0qBVxEmoIIjwi9Zw32T_
"""

import os
import random
import time
# УДАЛЕНО: from background import keep_alive
import pip
import telebot
from telebot import types
from flask import Flask, request # НОВЫЕ ИМПОРТЫ ДЛЯ ВЕБХУКОВ

# --- Установка зависимостей ---
# (Оставляем для совместимости, но на Render лучше использовать requirements.txt)
try:
    import telebot
    from flask import Flask, request
except ImportError:
    # Используем list для pip.main, чтобы избежать ошибок с None
    pip.main(['install', 'pytelegrambotapi', 'Flask'])
    import telebot
    from flask import Flask, request

# --- Конфигурация ---
BOT_USERNAME = "mrpolygraph_bot"

# ⚠️ ИСПОЛЬЗУЕМ ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ RENDER
# Это обязательно для безопасности и корректной работы на хостинге
API_TOKEN = os.environ.get('BOT_TOKEN', '8320176221:AAE-Yhi95YxEp5P7f1_q2da9VeQeskofRCI')
SERVER_URL = os.environ.get("SERVER_URL", "https://your-app-name.onrender.com")

WEBHOOK_PATH = '/'
WEBHOOK_URL = f"{SERVER_URL}{WEBHOOK_PATH}"

# ⚠️ Список путей к файлам стикеров (убедитесь, что они загружены в Render)
STICKER_FILES = [
    'sticker1.webp',
    'sticker2.webp'
]

bot = telebot.TeleBot(API_TOKEN)
app = Flask(__name__) # Инициализация Flask


# ----------------------------------------------------------------------
# 🌐 1. WEBHOOK ОБРАБОТЧИК (КРИТИЧНО ДЛЯ RENDER)
# ----------------------------------------------------------------------
@app.route(WEBHOOK_PATH, methods=['POST'])
def webhook():
    # Проверяем, что запрос действительно от Telegram
    if request.headers.get('content-type') == 'application/json':
        json_string = request.get_data().decode('utf-8')
        update = telebot.types.Update.de_json(json_string)
        bot.process_new_updates([update])
        return '', 200
    return 'OK', 200

# ----------------------------------------------------------------------
# 🖼️ 2. ФУНКЦИЯ ДЛЯ ОТПРАВКИ КОНТЕНТА
# ----------------------------------------------------------------------
def send_random_content_handler(message):
    """Общая функция для отправки случайного стикера как документа/файла."""

    if not STICKER_FILES:
         bot.reply_to(message, "🚫 Ошибка: Список стикеров пуст.")
         return

    reply_id = message.reply_to_message.message_id if message.reply_to_message else message.message_id
    selected_sticker_path = random.choice(STICKER_FILES)

    try:
        with open(selected_sticker_path, 'rb') as sticker_file:
            bot.send_document(
                chat_id=message.chat.id,
                document=sticker_file,
                reply_to_message_id=reply_id
            )
    except FileNotFoundError:
        bot.reply_to(message,
                     f"🚫 Ошибка: Не найден файл стикера '{selected_sticker_path}'.")
    except Exception as e:
        bot.reply_to(message,
                     f"🚫 Ошибка при отправке файла: {e}.")


# ----------------------------------------------------------------------
# 💡 3. INLINE-ОБРАБОТЧИК (Используем ваш текущий рабочий код)
# ----------------------------------------------------------------------
@bot.inline_handler(lambda query: True)
def query_text(inline_query):
    user_query = inline_query.query

    if user_query:
        title_text = f"Проверить: {user_query}"
        message_content = f"@{BOT_USERNAME} {user_query}"
    else:
        title_text = "Нажмите для проверки"
        message_content = f"@{BOT_USERNAME} "

    r = types.InlineQueryResultArticle(
        id='1',
        title=title_text,
        input_message_content=types.InputTextMessageContent(message_text=message_content)
    )

    try:
        # cache_time=0 для быстрого обновления
        bot.answer_inline_query(inline_query.id, [r], cache_time=0)
    except Exception as e:
        print(f"Ошибка в inline-обработчике: {e}")


# ----------------------------------------------------------------------
# 💬 4. ОСНОВНОЙ ОБРАБОТЧИК
# ----------------------------------------------------------------------

# 1. ОБРАБОТЧИК: /check как подпись к фото
@bot.message_handler(content_types=['photo'], regexp='^/check($|\\s.*)')
def handle_photo_caption_check(message):
    send_random_content_handler(message)


# 2. ОБРАБОТЧИК: команда /check
@bot.message_handler(commands=['check'])
def handle_check(message):
    send_random_content_handler(message)


# 3. ОБРАБОТЧИК: Все текстовые сообщения с тегом (@mrpgraph_bot)
@bot.message_handler(content_types=['text'])
def send_random_image(message):
    if f'@{BOT_USERNAME}' in message.text:
        send_random_content_handler(message)


# ----------------------------------------------------------------------
# 🚀 5. ЗАПУСК СЕРВЕРА (КРИТИЧНО ДЛЯ RENDER)
# ----------------------------------------------------------------------

if __name__ == "__main__":
    # 1. Установка вебхука перед запуском сервера
    print("Удаление старого вебхука...")
    bot.remove_webhook()
    time.sleep(1)
    print(f"Установка нового вебхука: {WEBHOOK_URL}")
    s = bot.set_webhook(url=WEBHOOK_URL)

    if s:
        print("Webhook установлен успешно!")
    else:
        print("Ошибка при установке Webhook.")

    # 2. Запуск Flask на порту, предоставленном Render (переменная окружения PORT)
    port = int(os.environ.get("PORT", 5000))
    # На Render, Flask будет запускаться через Gunicorn (см. Start Command)
    app.run(host='0.0.0.0', port=port)